### ISSUE TITLE
Feature request: Autoload on mason install/uninstall

### ISSUE THREAD

**Issue by Zeioth** [frostplexx/mason-bridge.nvim#4]
This snippet is present in [mason-null-ls](https://github.com/jay-babu/mason-null-ls.nvim)/[none-ls-autoload.nvim](https://github.com/Zeioth/none-ls-autoload.nvim) and maybe we could use it here too:

```lua
-- Extra feature: Also register source on mason package installed.
require('mason-registry'):on(
'package:install:success',
vim.schedule_wrap(function(pkg)
	get_none_ls_source_name(pkg.name):if_present(load_source)
end)
)

-- Extra feature: Also deregister source on mason package uninstalled.
require('mason-registry'):on(
'package:uninstall:success',
vim.schedule_wrap(function(pkg)
	 require('null-ls.sources').deregister(pkg.name)
end)
)
```

Maybe we could achieve something similar on `mason-bridge.nvim` so the registered clients are registered/deregistered when installing/uninstalling a mason package.

**Comment by Zeioth** [comment]
Because we only inject at startup time, maybe we could do this inside of an autocmd instead.

**Comment by Zeioth** [comment]
Maybe this could be achieved inside of LspAttach/LspDetach autocmds?

**Comment by frostplexx** [comment]
I don't think its possible to dynamically load formatters and linters like that as both conform and nvim-lint only take the `formatters_by_ft`/`linters_by_ft` tables as options in their setup functions. setup functions are only run once on startup of nvim.
For reference the [conform README](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#api) only mentions the `formatters_by_ft` in the setup function table. Similarly for nvim-lint adding the following snippet:
```lua
	require("mason-registry"):on(
		"package:install:success",
		vim.schedule_wrap(function()
			local lint = require("lint")
			local bridge = require("mason-bridge")
			bridge.force_reload()
			print(vim.inspect(require("mason-bridge").get_linters()))
			lint.linters_by_ft = bridge.get_linters()
		end)
	)
```
which sets the `linters_by_ft` again when a new package gets installed results in the following error:
```bash
Error executing vim.schedule lua callback: ...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:236: BufEnter Autocommands for "*": Vim(append):Error executing lua
 callback: /Users/daniel/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:84: attempt to index field 'linters_by_ft' (a nil value)
stack traceback:
        /Users/daniel/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:84: in function '_resolve_linter_by_ft'
        /Users/daniel/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:235: in function 'try_lint'
        /Users/daniel/.config/nvim/lua/plugins/lsp-lint-format.lua:86: in function </Users/daniel/.config/nvim/lua/plugins/lsp-lint-format.lua:85>
        [C]: in function 'nvim_win_close'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:236: in function <...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:233>
stack traceback:
        [C]: in function 'nvim_win_close'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:236: in function <...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:233>
```
which leads me to believe that nvim-lint also doesnt support dynamically updating its table.

**Comment by frostplexx** [comment]
@Zeioth as of 1.2.0 its possible to dynamically load linters and formatters. Please refer to the README for instructions!
