### ISSUE TITLE
Empty languages in registry

### ISSUE THREAD

**Issue by augustocdias** [frostplexx/mason-bridge.nvim#7]
Correct me if I'm wrong, but reading the code I got the impression that linters/formatters with empty arrays in the `languages` attribute will not be loaded (ex: https://github.com/mason-org/mason-registry/blob/main/packages/codespell/package.yaml).

I know I can set it manually with the `overrides` but it would be nice to have them being set for every filetype when empty.

**Comment by frostplexx** [comment]
This is correct. `mason-bridge` does not maintain a full mapping of languages to filetypes as discussed in #5 so not sure how it could set it for all filetypes as I couldn't find an nvim api that returns such thing. I think giving the user the ability to simply manually set the languages is sufficient until I (or someone else) can think of a good solution for generating/writing a complete mappings file.
